### ISSUE TITLE
handle ansi escape sequences

### ISSUE THREAD

**Issue by gilligan** [zimbatm/mdsh#20]
I just tried to use `mdsh` on a command that outputs some color and that currently has the undesired effect of yielding the escape codes verbatim in the output:

```
[32m[please]:[0m Running sanity checks:

- Nix installed :  [32mOK[0m
- contrail channel: [32mOK[0m
- contrail cache: [32mOK[0m
- kvm support: [32mOK[0m

All essential tests passed.
```

It would be great if there could be an option to filter those.

**Comment by zimbatm** [comment]
good idea
