### ISSUE TITLE
support expanding code blocks

### ISSUE THREAD

**Issue by juhp** [zimbatm/mdsh#30]
Just found this interesting project, thanks.
It seems close to what I need.

I think it would be really nice if mdsh could also support a code block format like this:

\`\`\`shellsession
$ echo hello; echo there
hello
there
\`\`\`

Instead of having to write:
\`$ echo hello\` as shellsession
\`\`\`shellsession
hello
\`\`\`

Particularly since the `as ...` will be rendered in the README, right? which is really not desirable.

**Comment by zimbatm** [comment]
That's an interesting idea, I wouldn't be against it if support for it was added.

One limitation is that it could only support blocks with a single command, as it's not possible to distinguish output that emits `$ ...`, but I think that's reasonable.

**Comment by deemp** [comment]
@juhp, I believe this issue was closed in https://github.com/zimbatm/mdsh/pull/59

**Comment by zimbatm** [comment]
yes, thank you
