### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by pesterhazy** [zimbatm/mdsh#6]
Nice tool

Here's how I built it

```
nix-shell -p cargo --command "cargo build"
```

Maybe add instructions along those lines?

**Comment by zimbatm** [comment]
thanks, fixed in caa9379c7a6a79c49ab6869b3c02da967c0e5926

**Comment by zimbatm** [comment]
let me know how it goes for you, if you hit any issues

**Comment by pesterhazy** [comment]
Works well for me, thanks!
